# Generated by Django 5.1.4 on 2025-08-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_channel",
            field=models.CharField(
                choices=[("COD", "Cash On Delivery"), ("ONLINE", "Online Payment")],
                default="COD",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="pg_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
