# Generated by Django 5.0.2 on 2024-04-28 03:27

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_username_alter_user_dob_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True, choices=[("AD", "Advocate"), ("CL", "Client")], max_length=2
            ),
        ),
    ]
