# Generated by Django 5.0.2 on 2024-05-15 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_advocateprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advocateprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advocate_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
