# Generated by Django 5.0.2 on 2024-06-06 14:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0009_practicearea_insert_rows"),
        ("users", "0007_phonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="advocateprofile",
            name="practice_areas",
            field=models.ManyToManyField(to="appointments.practicearea"),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="number",
            field=models.CharField(
                max_length=20,
                validators=[django.core.validators.MinLengthValidator(9)],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_number_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
