# Generated by Django 5.0.2 on 2024-06-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0009_practicearea_insert_rows"),
        ("users", "0008_advocateprofile_practice_areas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advocateprofile",
            name="practice_areas",
            field=models.ManyToManyField(
                related_name="advocate_profile_set", to="appointments.practicearea"
            ),
        ),
    ]
