# Generated by Django 5.0.2 on 2024-06-11 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_advocateprofile_practice_areas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="phone_number_set",
                related_query_name="phone_number",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
