# Generated by Django 5.0.2 on 2024-06-11 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_phonenumber_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_number_set",
                related_query_name="phone_number",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
