# Generated by Django 5.0.2 on 2024-10-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_phonenumber_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="advocateprofile",
            name="image",
            field=models.ImageField(blank=True, upload_to="profiles/"),
        ),
    ]
