# Generated by Django 5.0.2 on 2024-12-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_advocateprofile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("Asia/Kolkata", "Asia/Kolkata"),
                    ("America/Sao_Paulo", "America/Sao_Paulo"),
                    ("Asia/Jakarta", "Asia/Jakarta"),
                ],
                default="Asia/Kolkata",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="advocateprofile",
            name="educational_qualifications",
            field=models.CharField(
                max_length=30, verbose_name="Educational Qualifications"
            ),
        ),
        migrations.AlterField(
            model_name="advocateprofile",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="profiles/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="advocateprofile",
            name="practicing_from",
            field=models.DateField(verbose_name="Practicing From"),
        ),
        migrations.AlterField(
            model_name="advocateprofile",
            name="website_url",
            field=models.URLField(verbose_name="Website Url"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("AD", "Advocate"), ("CL", "Client")],
                max_length=2,
                verbose_name="role",
            ),
        ),
    ]
