# Generated by Django 5.0.2 on 2024-02-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicearea",
            name="name",
            field=models.CharField(max_length=25),
        ),
    ]
