# Generated by Django 5.0.2 on 2024-02-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0003_alter_practicearea_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicearea",
            name="name",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Name of Law"
            ),
        ),
    ]
