# Generated by Django 5.0.2 on 2024-03-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0004_alter_practicearea_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="practicearea",
            name="name",
            field=models.CharField(max_length=25, verbose_name="Name of Law"),
        ),
        migrations.AddConstraint(
            model_name="practicearea",
            constraint=models.UniqueConstraint(fields=("name",), name="pa_name_unq"),
        ),
    ]
