# Generated by Django 5.0.2 on 2024-03-01 02:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0005_alter_practicearea_name_practicearea_pa_name_unq"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="practicearea",
            table="practicearea",
        ),
    ]
