# Generated by Django 5.0.2 on 2024-03-01 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0006_alter_practicearea_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="practicearea",
            table="appointments_practicearea",
        ),
    ]
