# Generated by Django 5.0.2 on 2024-03-11 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0007_alter_practicearea_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="practicearea",
            options={
                "verbose_name": "Practice Area",
                "verbose_name_plural": "Practice Areas",
            },
        ),
    ]
