# Generated by Django 5.0.2 on 2024-03-16 17:13

from django.db import migrations


def insert_initial_practicearea(apps, schema):
    PracticeArea = apps.get_model("appointments", "PracticeArea")
    PracticeArea.objects.create(name="Test", description="Description")


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0008_alter_practicearea_options"),
    ]

    operations = [
        migrations.RunPython(insert_initial_practicearea)
    ]
