# Generated by Django 5.0.2 on 2024-12-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0012_alter_appointment_advocate_alter_appointment_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="start_at",
            field=models.DateTimeField(verbose_name="Start At"),
        ),
    ]
