# Generated by Django 5.1.4 on 2025-07-11 12:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=20)),
                ("address_line_1", models.CharField(max_length=50)),
                ("address_line_2", models.CharField(max_length=50)),
                (
                    "pincode",
                    models.CharField(
                        validators=[
                            django.core.validators.MinLengthValidator(6),
                            django.core.validators.MaxLengthValidator(6),
                        ]
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        validators=[django.core.validators.RegexValidator("^\\d{10}$")]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
